"use client";

import { Activity, BarChart3, ClipboardClock, FileHeart, FileText, Grid3X3, Plus, Search, Stethoscope } from "lucide-react";
import { ReactNode, useState } from "react";

import { Card, EmptyState, Field, Grid, Notice, PageTitle, SectionTitle, Subheading } from "./form-controls";
import styles from "./emergency.module.css";
import { EmergencyView } from "./types";

export function Dashboard({ navigate }: { navigate: (view: EmergencyView) => void }) {
  const cards: Array<[EmergencyView,string,string,ReactNode,string]> = [
    ["care","Atención médica","Crear una historia clínica con el FORM.008.",<Stethoscope key="i" />,"Comenzar atención"],
    ["pending","FORM.008 pendientes","Continuar historias guardadas sin finalizar.",<ClipboardClock key="i" />,"Ver pendientes"],
    ["histories","Historias clínicas","Buscar por fecha, identidad, enfermedad, CIE-10 o edad.",<FileHeart key="i" />,"Consultar historias"],
    ["epi","EPI epidemiológica","Crear fichas grupales o individuales.",<Activity key="i" />,"Crear documento EPI"],
    ["matrix","Matriz de guardia","Consolidar enfermedades, edad, sexo y condición final.",<Grid3X3 key="i" />,"Generar matriz"],
    ["certificate","Certificado médico","Generar certificados de atención o reposo.",<FileText key="i" />,"Crear certificado"],
  ];
  return <><PageTitle eyebrow="Área de emergencia" title="¿Qué desea realizar?" description="Seleccione una opción para registrar, continuar, consultar o consolidar atenciones." /><div className={styles.moduleGrid}>{cards.map(([view,title,description,icon,action]) => <button key={view} className={styles.moduleCard} onClick={() => navigate(view)}><span>{icon}</span><h2>{title}</h2><p>{description}</p><b>{action} →</b></button>)}</div></>;
}

export function PendingPage() { return <PageFrame title="FORM.008 pendientes" description="Seleccione una atención para continuar exactamente donde quedó."><div className={styles.searchRow}><div><Search size={18} /><input placeholder="Buscar por identificación, paciente o fecha" /></div></div><EmptyState>No existen FORM.008 pendientes mientras Supabase no esté conectado.</EmptyState></PageFrame>; }

export function HistoriesPage() {
  const [audit, setAudit] = useState(false);
  return <PageFrame title="Historias clínicas" description="Busque pacientes por fecha, identidad o rango específico de edad."><Grid columns={4}><Field label="Desde"><input type="date" /></Field><Field label="Hasta"><input type="date" /></Field><Field label="Identificación o paciente"><input type="search" /></Field><Field label="Unidad de edad"><select><option>Todas</option><option>HORAS</option><option>DÍAS</option><option>MESES</option><option>AÑOS</option></select></Field><Field label="Edad mínima"><input type="number" min={0} /></Field><Field label="Edad máxima"><input type="number" min={0} /></Field><button className={styles.primary}>Buscar</button><button className={styles.secondary}>Limpiar</button></Grid><div className={styles.actionStrip}><button onClick={() => setAudit(!audit)}>Ver auditoría de historia</button></div><EmptyState>No hay historias cargadas todavía.</EmptyState>{audit && <div className={styles.auditPanel}><SectionTitle title="Auditoría de la historia clínica" description="Versiones conservadas por modificación o eliminación lógica." /><EmptyState>La trazabilidad aparecerá al conectar la base de datos.</EmptyState></div>}</PageFrame>;
}

export function StatisticsPage() { return <><PageTitle eyebrow="Productividad" title="Panel estadístico" description="Resumen del profesional autenticado." /><div className={styles.statsGrid}>{[["FORM.008 creadas",0],["008 pendientes",0],["EPI individuales",0],["EPI grupales",0]].map(([label,value]) => <article key={String(label)}><BarChart3 /><div><small>{label}</small><strong>{value}</strong></div></article>)}</div><Card><SectionTitle title="Distribución de documentos" description="Los indicadores se actualizarán con los registros reales." /><div className={styles.chartPlaceholder}><strong>0</strong><span>documentos</span></div></Card></>; }

export function MatrixPage() { const [scope,setScope]=useState("MIS ATENCIONES"); return <PageFrame title="Matriz de entrega de guardia" description="Consolide atenciones por enfermedad, edad, sexo y condición final."><Grid><Field label="Fecha inicial" required><input type="date" /></Field><Field label="Fecha final" required><input type="date" /></Field><Field label="Atenciones incluidas"><select value={scope} onChange={(e)=>setScope(e.target.value)}><option>MIS ATENCIONES</option><option>ESTABLECIMIENTO</option></select></Field>{scope === "ESTABLECIMIENTO" && <Field label="Establecimiento"><select><option>Seleccione</option></select></Field>}</Grid><Notice tone="info"><span><b>Consolidación:</b> se utiliza un diagnóstico principal por atención y cada atención se cuenta una sola vez por enfermedad.</span></Notice><DocumentOutputs action="Generar matriz" /><div className={styles.statsGrid}><article><Activity /><div><strong>0</strong><small>atenciones incluidas</small></div></article><article><FileHeart /><div><strong>0</strong><small>enfermedades consolidadas</small></div></article></div></PageFrame>; }

export function CertificatePage() {
  const [show,setShow]=useState(false), [rest,setRest]=useState(false), [diagnoses,setDiagnoses]=useState(1);
  return <PageFrame title="Certificado médico" description="Busque o registre al paciente y genere el certificado de emergencia."><div className={styles.searchRow}><div><Search size={18}/><input maxLength={17} placeholder="Cédula, visa, pasaporte o carné" /></div><button onClick={()=>setShow(true)}>Buscar paciente</button></div>{show && <><Subheading>Datos del paciente</Subheading><PersonFields /><Subheading>Datos del certificado</Subheading><Grid><Field label="Especialidad"><select><option>MEDICINA GENERAL</option><option>MEDICINA FAMILIAR</option><option>OBSTETRICIA</option><option>ODONTOLOGÍA</option><option>PSICOLOGÍA</option></select></Field><Field label="Fecha de atención"><input type="date" /></Field><Field label="Hora de inicio"><input type="time" /></Field><Field label="Hora de finalización"><input type="time" /></Field><Field label="Reposo médico"><select value={rest?"SI":"NO"} onChange={(e)=>setRest(e.target.value==="SI")}><option>NO</option><option>SI</option></select></Field>{rest && <Field label="Días de reposo"><input type="number" min={1} max={365} /></Field>}</Grid><RepeaterHeader title="Diagnósticos" add={()=>setDiagnoses(diagnoses+1)} />{Array.from({length:diagnoses},(_,i)=><Diagnosis key={i}/>)}<label className={styles.inlineCheck}><input type="checkbox" defaultChecked /> Incluir automáticamente mi firma y sello</label><div className={styles.formActions}><button className={styles.primary}>Generar PDF</button><button className={styles.secondary}>Generar Excel</button></div></>}</PageFrame>;
}

export function ProfilePage() {
  const [tab,setTab]=useState("perfil"), [draw,setDraw]=useState(false), [deleteOpen,setDeleteOpen]=useState(false);
  return <><PageTitle eyebrow="Cuenta" title="Perfil y acceso" description="Información profesional, firma, sello y seguridad de la cuenta." /><Card><div className={styles.tabs}>{[["perfil","Mi perfil"],["ingreso","Ingresar"],["registro","Crear cuenta"],["recuperar","Recuperar clave"]].map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={tab===id?styles.tabActive:""}>{label}</button>)}</div>{tab === "perfil" && <><PersonNameFields /><Grid><Field label="Correo electrónico"><input type="email" /></Field><Field label="Cargo"><input readOnly defaultValue="MÉDICO" /></Field></Grid><Subheading>Establecimientos autorizados</Subheading><EmptyState>Las unidades asignadas aparecerán aquí.</EmptyState><Subheading>Cambiar contraseña</Subheading><Grid columns={3}><Field label="Clave actual"><input type="password" /></Field><Field label="Nueva clave"><input type="password" minLength={6} /></Field><Field label="Confirmar nueva clave"><input type="password" minLength={6} /></Field></Grid><SignatureFields draw={draw} setDraw={setDraw} /><div className={styles.formActions}><button className={styles.primary}>Guardar cambios</button></div><div className={styles.dangerZone}><h3>Eliminar cuenta</h3><p>La cuenta se desactivará conservando la trazabilidad clínica.</p><button onClick={()=>setDeleteOpen(true)}>Enviar código de eliminación</button>{deleteOpen && <><Field label="Código recibido"><input maxLength={6}/></Field><button>Confirmar eliminación</button></>}</div></>}{tab === "ingreso" && <><Grid><Field label="Cédula"><input maxLength={10}/></Field><Field label="Clave"><input type="password"/></Field></Grid><button className={styles.primary}>Ingresar a mi cuenta</button></>}{tab === "registro" && <><Grid><Field label="Cédula"><input maxLength={10}/></Field><Field label="Cargo"><select><option>MÉDICO</option><option>ADMISIONISTA</option></select></Field></Grid><PersonNameFields /><Field label="Correo"><input type="email" /></Field><Field label="Establecimiento solicitado"><input type="search" placeholder="Buscar establecimiento, unicódigo o ubicación" /></Field><SignatureFields draw={draw} setDraw={setDraw}/><Grid><Field label="Clave"><input type="password" minLength={6}/></Field><Field label="Confirmar clave"><input type="password" minLength={6}/></Field></Grid><button className={styles.primary}>Crear cuenta</button></>}{tab === "recuperar" && <><Field label="Correo registrado"><input type="email" /></Field><button className={styles.primary}>Enviar código</button><Grid><Field label="Código de 6 dígitos"><input maxLength={6}/></Field><Field label="Nueva clave"><input type="password"/></Field></Grid></>}</Card></>;
}

export function AdmissionPage() { const [show,setShow]=useState(false), [without,setWithout]=useState(false); return <PageFrame title="Panel de admisión" description="Busque y actualice datos generales y de admisión."><div className={styles.searchRow}><div><Search size={18}/><input maxLength={17}/></div><button onClick={()=>setShow(true)}>Buscar paciente</button><button className={styles.secondary} onClick={()=>{setWithout(true);setShow(true)}}>Paciente sin documento</button></div>{show && <><Grid><Field label="Identificación"><input readOnly={without}/></Field><Field label="Tipo de documento"><select><option>CC/CI</option><option>VISA</option><option>PASAPORTE</option><option>CARNÉ DE REFUGIADO</option><option>SIN DOCUMENTO</option></select></Field></Grid><PersonNameFields/><Grid><Field label="Fecha de nacimiento"><input type="date"/></Field><Field label="Sexo"><select><option>MASCULINO</option><option>FEMENINO</option></select></Field><Field label="Teléfono celular"><input/></Field><Field label="Provincia"><input/></Field><Field label="Cantón"><input/></Field><Field label="Parroquia"><input/></Field><Field label="Dirección domiciliaria" wide><input/></Field></Grid><Subheading>Datos de admisión</Subheading><Grid><Field label="Fecha de admisión"><input type="date"/></Field><Field label="Hora"><input type="time"/></Field><Field label="Historia en establecimiento"><select><option>SI</option><option>NO</option></select></Field><Field label="Condición de llegada"><select><option>ESTABLE</option><option>INESTABLE</option><option>FALLECIDO</option></select></Field><Field label="Motivo de atención" wide><textarea rows={4}/></Field></Grid>{without && <Notice tone="warning"><Grid><Field label="Tipo de documento definitivo"><select><option>CC/CI</option><option>VISA</option><option>PASAPORTE</option></select></Field><Field label="Número definitivo"><input/></Field></Grid></Notice>}<button className={styles.primary}>Actualizar admisión</button></>}</PageFrame>; }

export function PatientsPage() { const [show,setShow]=useState(false); return <PageFrame title="Gestión de pacientes" description="Consulte y actualice la ficha completa del paciente."><div className={styles.searchRow}><div><Search size={18}/><input maxLength={17}/></div><button onClick={()=>setShow(true)}>Buscar paciente</button></div>{show && <><PersonFields full/><Subheading>Residencia</Subheading><AddressFields/><Subheading>Contacto de emergencia</Subheading><Grid><Field label="Nombre"><input/></Field><Field label="Parentesco"><input/></Field><Field label="Dirección"><input/></Field><Field label="Teléfono"><input/></Field></Grid><button className={styles.primary}>Guardar ficha del paciente</button></>}</PageFrame>; }

export function EpiPage() {
  const [show,setShow]=useState(false), [type,setType]=useState("GRUPAL"), [samples,setSamples]=useState(1), [contacts,setContacts]=useState(1);
  return <PageFrame title="Investigación epidemiológica" description="Complete la EPI grupal o individual recuperando datos de la atención."><div className={styles.searchRow}><div><Search size={18}/><input maxLength={17} placeholder="Cédula, pasaporte, visa o carné"/></div><button onClick={()=>setShow(true)}>Buscar paciente</button></div>{show && <><div className={styles.modeSwitch}><label><input type="radio" checked={type==="GRUPAL"} onChange={()=>setType("GRUPAL")}/><span><b>EPI grupal</b><small>Notificación y cierre de caso</small></span></label><label><input type="radio" checked={type==="INDIVIDUAL"} onChange={()=>setType("INDIVIDUAL")}/><span><b>EPI individual</b><small>Investigación clínico-epidemiológica</small></span></label></div><EpiPatient/><EpiUnit/>{type === "GRUPAL" ? <EpiGroup samples={samples} setSamples={setSamples}/> : <EpiIndividual contacts={contacts} setContacts={setContacts}/>}<DocumentOutputs action="Generar EPI seleccionada"/></>}</PageFrame>;
}

function EpiPatient() { return <Details title="1. Datos reutilizados del paciente" open><Notice tone="info"><span>Revise la información recuperada antes de generar el documento.</span></Notice><Grid><Field label="Nombre completo" wide><input readOnly/></Field><Field label="Número de identificación"><input readOnly/></Field><Field label="Sexo"><select><option>Seleccione</option><option>MASCULINO</option><option>FEMENINO</option></select></Field><Field label="Fecha de nacimiento"><input type="date"/></Field><Field label="Edad calculada"><input readOnly/></Field><Field label="Unidad de edad"><input readOnly/></Field><Field label="Nacionalidad"><input/></Field><Field label="Estado civil"><input/></Field><Field label="Autoidentificación étnica"><input/></Field><Field label="Escolaridad"><input/></Field><Field label="Ocupación"><input/></Field><Field label="Teléfono"><input/></Field><Field label="Provincia"><input/></Field><Field label="Cantón"><input/></Field><Field label="Parroquia"><input/></Field><Field label="Barrio/localidad"><input/></Field><Field label="Dirección consolidada" wide><input readOnly/></Field><Field label="Madre, responsable o contacto" wide><input/></Field></Grid></Details>; }
function EpiUnit() { return <Details title="2. Unidad y diagnóstico" open><Grid><Field label="Diagnóstico para la EPI" wide><select><option>Seleccione un diagnóstico</option></select></Field><Field label="Fecha de atención"><input type="date"/></Field><Field label="Hora de atención"><input type="time"/></Field><Field label="Fecha de investigación"><input type="date"/></Field><Field label="Semana epidemiológica"><input type="number" min={1} max={53}/></Field><Field label="Unidad que notifica/investiga" wide><input/></Field><Field label="Institución"><select><option>MSP</option><option>IESS</option><option>FFAA</option><option>POLICÍA</option><option>JBGI</option><option>MEC</option><option>DRS</option><option>PRIVADO</option><option>ONG</option></select></Field><Field label="Provincia de la unidad"><input/></Field><Field label="Cantón de la unidad"><input/></Field><Field label="Parroquia de la unidad"><input/></Field><Field label="Nombre de quien notifica" wide><input/></Field></Grid></Details>; }
function EpiGroup({samples,setSamples}:{samples:number;setSamples:(n:number)=>void}) { return <><Details title="III. Datos clínicos y embarazo" open><Grid><Field label="Fecha de inicio de síntomas"><input type="date"/></Field><Field label="Lugar probable de infección" wide><input/></Field><YesNo label="Embarazada" na/><Field label="Semanas de gestación"><input type="number" min={0} step="0.1"/></Field></Grid></Details><Details title="IV–V. Muestras y laboratorio"><Grid><YesNo label="Tomó muestra"/><Field label="Fecha de toma"><input type="date"/></Field><Field label="Tipo de muestra 1"><input/></Field><Field label="Tipo de muestra 2"><input/></Field><Field label="Fecha muestra 2"><input type="date"/></Field><Field label="Tipo de muestra 3"><input/></Field><Field label="Fecha muestra 3"><input type="date"/></Field><Field label="Nombre y ubicación del laboratorio" wide><input/></Field><Field label="Resultado"><select><option>Seleccione</option><option>POSITIVO</option><option>NEGATIVO</option><option>DUDOSO</option></select></Field><Field label="Agente encontrado"><input/></Field><Field label="Segundo agente"><input/></Field><Field label="Observaciones del laboratorio" wide><textarea rows={4}/></Field></Grid><RepeaterHeader title="Procesamiento de muestras" add={()=>setSamples(Math.min(3,samples+1))}/>{Array.from({length:samples},(_,i)=><Sample key={i}/>)}</Details><Details title="VI–VIII. Investigación, evolución y cierre"><Grid><YesNo label="Se realizó investigación"/><Field label="Fecha de investigación"><input type="date"/></Field><Field label="N.º contactos sintomáticos"><input type="number" min={0}/></Field><Field label="Evolución"><select><option>AMBULATORIO</option><option>HOSPITALIZACIÓN</option><option>UCI</option></select></Field><Field label="Condición final"><select><option>VIVO</option><option>CON DISCAPACIDAD</option><option>MUERTO</option></select></Field><Field label="Fecha de fallecimiento"><input type="date"/></Field><Field label="Clasificación final"><select><option>CONFIRMADO</option><option>DESCARTADO</option><option>NO CONCLUYENTE</option></select></Field><Field label="Confirmado por"><select><option>LABORATORIO</option><option>CLÍNICO</option><option>NEXO EPIDEMIOLÓGICO</option></select></Field><Field label="Diagnóstico final" wide><input/></Field><Field label="Fecha de cierre"><input type="date"/></Field><Field label="Responsable epidemiológico" wide><input/></Field></Grid></Details></>; }

function EpiIndividual({contacts,setContacts}:{contacts:number;setContacts:(n:number)=>void}) { const symptoms=["ADENOPATÍAS","CIANOSIS","ESCALOFRÍOS","PRURITO","ALTERACIÓN NEUROLÓGICA PERIFÉRICA","CONVULSIONES","ESPASMO MUSCULAR","RIGIDEZ MUSCULAR","ALTERACIÓN NEUROLÓGICA CENTRAL","DESHIDRATACIÓN","ESTRIDOR RESPIRATORIO","SANGRADOS","ANOREXIA","DIARREA","FIEBRE","TOS","APNEA","DIFICULTAD RESPIRATORIA","ICTERICIA","TRISMUS","ARTRALGIA","DOLOR ABDOMINAL","MIALGIAS","VISIÓN BORROSA","ASCITIS","DOLOR DE GARGANTA","NÁUSEAS/VÓMITOS","ONCOCERCOMAS","CEFÁLEA","ERUPCIÓN","PARÁLISIS","SUDORACIÓN NOCTURNA"]; return <><Details title="III. Cuadro clínico, signos y síntomas" open><Grid><Field label="Fecha de inicio del cuadro"><input type="date"/></Field><Field label="Hora de inicio"><input type="time"/></Field><Field label="Fecha de síntoma relevante"><input type="date"/></Field><Field label="Hora del síntoma relevante"><input type="time"/></Field><Field label="N.º de días"><input type="number" min={0}/></Field></Grid><CheckGrid items={symptoms}/><Field label="Otros signos y síntomas"><input/></Field><Field label="Caracterización del cuadro clínico"><textarea rows={10}/></Field></Details><Details title="Tratamiento, controles y hospitalización"><Grid><YesNo label="Recibió tratamiento"/><Field label="Tiempo de tratamiento"><input/></Field><Field label="Tratamiento recibido" wide><textarea rows={4}/></Field></Grid><CheckGroup title="Evolución" items={["MEJORÓ","IGUALES CONDICIONES","EMPEORÓ"]}/><CheckGroup title="Lugar donde recibió tratamiento" items={["DOMICILIO","UNIDADES DE SALUD DEL MSP","FARMACIA","OTRAS UNIDADES DEL SECTOR PÚBLICO","UNIDADES DE SALUD PRIVADAS"]}/><Grid><YesNo label="Tuvo controles"/><Field label="N.º de controles"><input type="number" min={0}/></Field><Field label="Quién recetó" wide><input/></Field><YesNo label="Fue hospitalizado"/><Field label="Fecha de hospitalización"><input type="date"/></Field><Field label="N.º historia hospital"><input/></Field><Field label="Servicio"><input/></Field><Field label="Nombre del hospital" wide><input/></Field><YesNo label="Red privada"/><YesNo label="Ingresó a UCI"/><Field label="Condición final"><select><option>VIVO</option><option>MUERTO</option></select></Field><YesNo label="Discapacidad"/><Field label="Fecha de fallecimiento"><input type="date"/></Field></Grid></Details><EpiBackground/><EpiRisk/><Details title="Contactos durante incubación/transmisibilidad"><RepeaterHeader title="Contactos" add={()=>setContacts(Math.min(8,contacts+1))}/>{Array.from({length:contacts},(_,i)=><Contact key={i}/>)}</Details><EpiLaboratory/><EpiActivities/></>; }

function EpiBackground(){return <Details title="IV. Antecedentes epidemiológicos"><Grid><Field label="Antecedente vacunal"><select><option>DESCONOCE</option><option>SI</option><option>NO</option></select></Field><Field label="Fecha de última dosis"><input type="date"/></Field><Field label="N.º dosis recibidas"><input type="number" min={0}/></Field></Grid><CheckGroup title="Vacunas" items={["BCG","HB","ROTA","OPV","PENTA","INFLUENZA","NEUMOCOCO CONJUGADO","SR","FA","DT","DPT","D-T","SRP","VARICELA","NEUMOCOCO POLISACÁRIDO","OTRAS"]}/><CheckGroup title="Fuente de información" items={["TARJETA DE VACUNACIÓN","REGISTRO EN EL SERVICIO DE SALUD","VERBAL"]}/><CheckGroup title="Antecedentes y origen de contacto" items={["ANIMAL VIVO","ANIMALES MUERTOS","AGUA/SUELOS","BASURALES","NINGUNO","METANOL","PERSONA SINTOMÁTICA","ALIMENTOS","PLAGUICIDAS","OTRO ORIGEN DEL CONTACTO","METALES PESADOS","SOLVENTES"]}/><Grid><Field label="Lugar geográfico del contacto"><input/></Field><Field label="Forma de contacto"><input/></Field><Field label="Origen/tipo/nombre del contacto" wide><input/></Field><Field label="Fecha de contacto"><input type="date"/></Field><Field label="Hora de contacto"><input type="time"/></Field></Grid><CheckGroup title="Procedencia de agua/alimento" items={["CASA","RESTAURANTE","CALLE","REUNIÓN SOCIAL"]}/><Grid><Field label="Otra procedencia" wide><input/></Field><Field label="Tipo de exposición"><select><option>ACCIDENTAL</option><option>OCUPACIONAL</option><option>DESCONOCIDA</option><option>INTENTO SUICIDA</option><option>REACCIÓN ADVERSA</option></select></Field><Field label="Otra exposición"><input/></Field></Grid></Details>}
function EpiRisk(){return <Details title="Viajes, comorbilidades y factores de riesgo"><Grid><YesNo label="Transfusión sanguínea"/><YesNo label="Embarazada"/><Field label="Semanas de gestación"><input type="number" min={0} step="0.1"/></Field><YesNo label="Quimioterapia"/><YesNo label="Antecedente de viaje"/><Field label="Lugar del viaje"><input/></Field><Field label="Viaje desde"><input type="date"/></Field><Field label="Viaje hasta"><input type="date"/></Field><YesNo label="Otros enfermos con iguales síntomas"/></Grid><CheckGroup title="Dónde están los otros enfermos" items={["CASA","BARRIO","LUGAR DE TRABAJO","ESTABLECIMIENTO DE SALUD","DESCONOCIDO","OTRO"]}/><Grid><Field label="Origen del caso"><select><option>NO APLICA</option><option>AUTÓCTONO</option><option>IMPORTADO</option><option>INTRODUCIDO</option><option>INDICATIVO</option><option>INDUCIDO</option></select></Field><YesNo label="Comorbilidades"/><Field label="Detalle de comorbilidades" wide><input/></Field></Grid><CheckGroup title="Factores de riesgo y transmisión" items={["HIJOS DE MADRES INFECTADA POR VHB","TRANSFUSIONES","HEMODIÁLISIS","TRASPLANTE DE ÓRGANOS","DROGAS INYECTABLES","TATUAJES Y PERFORACIONES","SEXO SOLO CON HOMBRES","SEXO SOLO CON MUJERES","SEXO CON HOMBRES Y MUJERES","PINCHAZOS CON AGUJA","COMPARTIR CEPILLOS Y AFEITADORAS","HIJO DE MADRE INFECTADA POR VHC","CIRUGÍAS","TRATAMIENTOS DENTALES","MATERNO INFANTIL","HORIZONTAL","SEXUAL","TRANSFUSIONES SANGUÍNEAS","PERCUTÁNEA","NOSOCOMIAL"]}/><Field label="Caracterización de factores de riesgo"><textarea rows={7}/></Field></Details>}
function EpiLaboratory(){return <Details title="V. Laboratorio y clasificación final"><Grid><YesNo label="Se tomó muestra"/><Field label="Fecha de muestra"><input type="date"/></Field><YesNo label="Muestra antes del tratamiento"/><Field label="Tipo de muestra"><input/></Field><Field label="Agente encontrado"><input/></Field><Field label="Técnica utilizada"><input/></Field><Field label="Resultado de laboratorio" wide><textarea rows={3}/></Field><Field label="Lugar de atención"><select><option>AMBULATORIA</option><option>HOSPITALIZACIÓN</option><option>UCI</option><option>NO APLICA</option></select></Field><YesNo label="Cumple definición de caso"/><Field label="Condición final"><select><option>VIVO</option><option>CON DISCAPACIDAD</option><option>MUERTO</option></select></Field></Grid><CheckGroup title="Clasificación final" items={["DESCARTADO","NO CONCLUYENTE","CONFIRMADO","CON RIESGO","SIN RIESGO","RELACIONADO CON LA VACUNA","COINCIDENTE","RELACIONADO CON EL PROGRAMA DE VACUNA"]}/><Field label="Diagnóstico definitivo"><input/></Field><CheckGroup title="Confirmado por" items={["LABORATORIO","CLÍNICA","NEXO EPIDEMIOLÓGICO"]}/></Details>}
function EpiActivities(){return <Details title="VI. Actividades de control y responsable"><ActivityRows title="Actividades generales" items={["VISITA DOMICILIARIA","BÚSQUEDA ACTIVA DE CASOS","SEGUIMIENTO DE CONTACTO"]}/><ActivityRows title="Actividades específicas" items={["VACUNACIÓN DE BLOQUEO","PROFILAXIS A LOS CONTACTOS","MONITOREO RÁPIDO DE COBERTURAS","TRATAMIENTO DE CRIADEROS DE VECTORES"]}/><Field label="Otras actividades"><textarea rows={6}/></Field><Grid><Field label="Responsable" wide><input/></Field><Field label="Fecha del responsable"><input type="date"/></Field></Grid></Details>}

function PageFrame({title,description,children}:{title:string;description:string;children:ReactNode}){return <><PageTitle eyebrow="Módulo de emergencia" title={title} description={description}/><Card>{children}</Card></>}
function Details({title,children,open=false}:{title:string;children:ReactNode;open?:boolean}){return <details className={styles.details} open={open}><summary>{title}</summary><div>{children}</div></details>}
function DocumentOutputs({action}:{action:string}){return <div className={styles.exportPanel}><div><h3>Formatos de descarga</h3><p>Seleccione uno o ambos.</p></div><label><input type="checkbox" defaultChecked/> PDF</label><label><input type="checkbox"/> Excel</label><button className={styles.primary}>{action}</button></div>}
function PersonNameFields(){return <Grid><Field label="Primer nombre"><input/></Field><Field label="Segundo nombre"><input/></Field><Field label="Primer apellido"><input/></Field><Field label="Segundo apellido"><input/></Field></Grid>}
function PersonFields({full=false}:{full?:boolean}){return <><Grid><Field label="Tipo de identificación"><select><option>CC/CI</option><option>VISA</option><option>PASAPORTE</option><option>CARNÉ DE REFUGIADO</option><option>SIN DOCUMENTO</option></select></Field><Field label="Número de identificación"><input maxLength={17}/></Field></Grid><PersonNameFields/><Grid><Field label="Estado civil"><select><option>Seleccione</option><option>SOLTERO/A</option><option>CASADO/A</option><option>DIVORCIADO/A</option><option>VIUDO/A</option><option>UNIÓN LIBRE</option></select></Field><Field label="Sexo"><select><option>MASCULINO</option><option>FEMENINO</option></select></Field><Field label="Fecha de nacimiento"><input type="date"/></Field>{full&&<Field label="Hora de nacimiento"><input type="time"/></Field>}<Field label="Lugar de nacimiento"><input/></Field><Field label="Nacionalidad"><input defaultValue="ECUATORIANA"/></Field><Field label="Edad"><input type="number" min={0}/></Field><Field label="Unidad de edad"><select><option>AÑOS</option><option>MESES</option><option>DÍAS</option><option>HORAS</option></select></Field>{full&&<><Field label="Grupo prioritario"><input/></Field><Field label="Autoidentificación étnica"><input/></Field><Field label="Nacionalidad étnica"><input/></Field><Field label="Pueblo"><input/></Field><Field label="Nivel de educación"><input/></Field><Field label="Estado educativo"><input/></Field><Field label="Tipo de empresa"><input/></Field><Field label="Ocupación/profesión"><input/></Field><Field label="Seguro de salud"><input/></Field><Field label="Teléfono fijo"><input/></Field></>}<Field label="Teléfono celular"><input/></Field></Grid></>}
function AddressFields(){return <Grid><Field label="Provincia"><input/></Field><Field label="Cantón"><input/></Field><Field label="Parroquia"><input/></Field><Field label="Barrio/sector"><input/></Field><Field label="Calle principal"><input/></Field><Field label="Calle secundaria"><input/></Field><Field label="Referencia domiciliaria" wide><input/></Field></Grid>}
function SignatureFields({draw,setDraw}:{draw:boolean;setDraw:(v:boolean)=>void}){return <><Subheading>Firma y sello</Subheading><div className={styles.modeSwitch}><label><input type="radio" checked={!draw} onChange={()=>setDraw(false)}/> Subir imagen</label><label><input type="radio" checked={draw} onChange={()=>setDraw(true)}/> Dibujar firma</label></div><Grid>{draw?<div className={styles.signaturePad}>Área para dibujar la firma</div>:<Field label="Firma profesional"><input type="file" accept="image/*"/></Field>}<Field label="Sello profesional"><input type="file" accept="image/*"/></Field><Field label="Quitar fondo de las imágenes" wide><input type="range" min={0} max={255}/></Field></Grid></>}
function RepeaterHeader({title,add}:{title:string;add:()=>void}){return <div className={styles.repeaterTitle}><h3>{title}</h3><button onClick={add}><Plus size={16}/> Agregar</button></div>}
function Diagnosis(){return <div className={styles.repeatRow}><Field label="CIE-10"><input/></Field><Field label="Descripción"><input/></Field><button className={styles.removeButton}>Quitar</button></div>}
function YesNo({label,na=false}:{label:string;na?:boolean}){return <Field label={label}><select>{na&&<option>NO APLICA</option>}<option>NO</option><option>SI</option></select></Field>}
function CheckGrid({items}:{items:string[]}){return <div className={styles.epiChecks}>{items.map(x=><label key={x}><input type="checkbox"/> {x}</label>)}</div>}
function CheckGroup({title,items}:{title:string;items:string[]}){return <div className={styles.checkGroup}><h4>{title}</h4><CheckGrid items={items}/></div>}
function Sample(){return <div className={styles.epiRepeat}><input placeholder="Tipo de muestra"/><Field label="Recepción"><input type="date"/></Field><Field label="Adecuada"><select><option>SI</option><option>NO</option></select></Field><Field label="Procesamiento"><input type="date"/></Field><Field label="Resultado"><input type="date"/></Field><button className={styles.removeButton}>Quitar</button></div>}
function Contact(){return <div className={styles.epiRepeat}><input placeholder="Nombre"/><input type="number" min={0} placeholder="Edad"/><select><option>M</option><option>F</option></select><input placeholder="Relación con el caso"/><input placeholder="Dirección / teléfono"/><input placeholder="Lugar de contacto"/><select><option>NO</option><option>SI</option></select><input type="date"/><input placeholder="Observaciones"/><button className={styles.removeButton}>Quitar</button></div>}
function ActivityRows({title,items}:{title:string;items:string[]}){return <div className={styles.activities}><h4>{title}</h4>{items.map(x=><div key={x}><b>{x}</b><select><option>NO</option><option>SI</option></select><input type="date"/><input placeholder="Observaciones"/></div>)}</div>}
